apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slash-llm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LikeLionTeam4/slash-infra.git
    targetRevision: dev
    path: helm/slash-llm
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
