apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slash-api.fullname" . }}
  labels:
    {{- include "slash-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "slash-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slash-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "slash-api.fullname" . }}
      containers:
        - name: slash-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- with .Values.env }}
          env:
            {{- range $k, $v := . }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
