{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "slash-api.fullname" . }}
  labels:
    {{- include "slash-api.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "slash-api.fullname" . }}
{{- end }}
