apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slash-api.fullname" . }}
  labels:
    {{- include "slash-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
