apiVersion: v1
kind: Service
metadata:
  name: {{ include "slash-nlu.fullname" . }}
  labels:
    {{- include "slash-nlu.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "slash-nlu.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
